name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  terraform-apply:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials using temporary credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Initialize and Apply Terraform
        run: |
          cd terraform
          terraform init -upgrade
          terraform apply -auto-approve -var-file="variables.tfvars"

      - name: Extract Outputs
        id: outputs
        run: |
          cd terraform
          echo "CLUSTER_NAME=$(terraform output -raw cluster_id)" >> $GITHUB_ENV
          echo "AWS_REGION=$(terraform output -raw aws_region)" >> $GITHUB_ENV
          echo "OIDC_ROLE_ARN=$(terraform output -raw oidc_role_arn)" >> $GITHUB_ENV
          echo "DEPLOYMENT_NAME=$(terraform output -raw deployment_name)" >> $GITHUB_ENV
          echo "SERVICE_NAME=$(terraform output -raw service_name)" >> $GITHUB_ENV
          echo "SERVICE_IP=$(terraform output -raw service_ip)" >> $GITHUB_ENV
          echo "API_LB_DNS=$(terraform output -raw api_lb_dns)" >> $GITHUB_ENV

  build-and-deploy:
    runs-on: ubuntu-latest

    needs: terraform-apply  # This job runs after the terraform-apply job completes successfully

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ env.OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.16'

      - name: Build
        run: go build -v ./...

      - name: Run tests
        run: go test -v ./...

      - name: Deploy to EKS
        run: |
          aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ env.AWS_REGION }}
          kubectl rollout restart deployment ${{ env.DEPLOYMENT_NAME }}