name: Destroy K8s Resources

on:
  workflow_dispatch:

jobs:
  destroy-k8s:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive
        
      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '1.5.7'
          
      - name: Delete Kubernetes Deployment
        run: |
          # Connect to EKS
          aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}
          
          # Delete the deployment
          kubectl delete deployment golang-api-deploy --ignore-not-found=true
          
      - name: Initialize and Destroy K8s Module
        run: |
          cd terraform
          terraform init -upgrade || exit 1
          
          # Destroy only the k8s module
          terraform destroy -target=module.ilios_k8s -var-file="terraform.tfvars" -auto-approve || exit 1
          
          echo "K8s resources have been destroyed"