name: Terraform Apply

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform with tfvars
        run: terraform apply -var-file="terraform/*.tfvars" -auto-approve

      - name: Extract Outputs
        id: outputs
        run: |
          echo "::set-output name=cluster_name::$(terraform output -raw cluster_name)"
          echo "::set-output name=aws_region::$(terraform output -raw aws_region)"
          echo "::set-output name=oidc_role_arn::$(terraform output -raw oidc_role_arn)"

      - name: Set Repository Variables
        run: |
          echo "AWS_REGION=${{ steps.outputs.outputs.aws_region }}" >> $GITHUB_ENV
          echo "CLUSTER_NAME=${{ steps.outputs.outputs.cluster_name }}" >> $GITHUB_ENV
          echo "OIDC_ROLE_ARN=${{ steps.outputs.outputs.oidc_role_arn }}" >> $GITHUB_ENV